export type CoreEventType =
    | 'entityCreated'
    | 'entityUpdated'
    | 'entityDeleted'
    | 'actionCreated'
    | 'actionUpdated'
    | 'actionDeleted'
    | 'hookCreated'
    | 'hookUpdated'
    | 'hookDeleted'
    | 'eventCreated'
    | 'eventDeleted'
    | 'measurementCreated'
    | 'measurementDeleted'
    | 'measurementUpdated';
